/**
 * MIT License
 * <p>
 * Bot Character Framework - Java framework for building smart bots
 * Copyright (c) 2017 Dmitry Berezovsky https://github.com/corvis/bot-character-framework
 * <p>
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * <p>
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 */
package org.bcf.domain.base;

/**
 * Base class for entities generated by probability model.
 *
 * @author Dmitry Berezovsky (corvis)
 */
public abstract class BasePredictedEntity {
    private String sourceId;
    private float confidenceLevel;

    /**
     * Identifier of the model or extractor produced this entity
     * @return
     */
    public String getSourceId() {
        return sourceId;
    }

    public BasePredictedEntity setSourceId(String source) {
        this.sourceId = source;
        return this;
    }

    /**
     * Level of confidence. Should be between 0 and 1.
     * Higher value means higher probability
     *
     * @return
     */
    public float getConfidenceLevel() {
        return confidenceLevel;
    }

    public BasePredictedEntity setConfidenceLevel(float confidenceLevel) {
        this.confidenceLevel = confidenceLevel;
        return this;
    }
}
